package scalargo

// List of known clients
const (
	ClientAsyncHTTP    = "asynchttp"
	ClientAxios        = "axios"
	ClientCljHTTP      = "clj_http"
	ClientCoHTTP       = "cohttp"
	ClientCurl         = "curl"
	ClientFetch        = "fetch"
	ClientGuzzle       = "guzzle"
	ClientHTTP1        = "http1.1"
	ClientHTTPClient   = "httpclient"
	ClientHTTP2        = "http2"
	ClientHttpie       = "httpie"
	ClientHttr         = "httr"
	ClientJquery       = "jquery"
	ClientLibCurl      = "libcurl"
	ClientNative       = "native"
	ClientNetHTTP      = "nethttp"
	ClientNsurlSession = "nsurlsession"
	ClientOkHTTP       = "okhttp"
	ClientOkhttp       = "okhttp"
	ClientPython3      = "python3"
	ClientRequest      = "request"
	ClientRequests     = "requests"
	ClientRestMethod   = "restmethod"
	ClientRestSharp    = "restsharp"
	ClientUndici       = "undici"
	ClientUnirest      = "unirest"
	ClientWebRequest   = "webrequest"
	ClientWget         = "wget"
	ClientXhr          = "xhr"
	ClientHTTP         = "http"
	ClientOfetch       = "ofetch"
	ClientHTTPXSync    = "httpxsync"
	ClientHTTPXAsync   = "httpxasync"
	ClientReqWest      = "reqwest"
)
