name: "Build and Release"

on:
  push:
    branches:
      - master
      - main

jobs:
  go-lint:
    name: "GoLang Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get . && go install gotest.tools/gotestsum@latest
      - name: Run unit tests
        run: gotestsum --format testname

  Release:
    name: Release
    needs: [ unit-tests, go-lint ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run semantic-release
        if: github.repository == 'bdpiprava/scalar-go' && github.event_name == 'push'
        run: npx semantic-release@v19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-docs:
    name: Generate Docs
    needs: [ Release ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get .
      - name: Generate Docs
        run: make generate-doc
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './main/static'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4