name: "PR: Checks"

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  go-lint:
    name: "GoLang Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get . && go install gotest.tools/gotestsum@latest
      - name: Run unit tests
        run: gotestsum --format testname